steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sample']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'sample'
  - '--image=gcr.io/$PROJECT_ID/sample'
  - '--region=asia-northeast1'
  - '--platform=managed'
  - '--no-allow-unauthenticated'
